package com.linuxtips.produtos_api.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.document.Table;

@DynamoDBTable(tableName = "produto")

public class Produto {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String produtoId;

    @DynamoDBAttribute
    private String preco;

       public Produto() {
    }

    public String getProdutoId() {
        return produtoId;
    }

    public void setProdutoId(String produtoId) {
        this.produtoId = produtoId;
    }

    public String getPreco() {
        return preco;
    }



}
